### ISSUE TITLE
Cannot compile App. Missing Podfile in root directory.

### ISSUE THREAD

**Issue by asm09fsu** [camellk24/CrackiOSInterview#1]
It seems this project is using Cocoapods, yet here is a missing Podfile in the root directory, which does not allow me to be able to run the application. Make sure if you are using a gitignore (which it doesn't look like you are), you do not include the Podfile file, but you can include the Pods directory as ignoring. 

If you are not using Cocoapods anymore, please be sure to remove traces of Cocoapods from the project.

**Comment by camellk24** [comment]
Podfile added. Now it should be able to compile correctly. Thanks!
