### ISSUE TITLE
[AutoLayout] No support with AutoLayout to show the email/password textfields on keyboard appearance.

### ISSUE THREAD

**Issue by asm09fsu** [camellk24/CrackiOSInterview#2]
On the login screen, when a user taps the email or password text fields, I would expect the keyboard to come up from the bottom, but also the text fields themselves to be visible just about the keyboard frame. Right now when the keyboard comes up, the text fields are behind the keyboard, making them not visible when editing.

**Comment by camellk24** [comment]
Sorry for the issues on login page. Will fix it soon and allow facebook login as well. Thanks!

**Comment by camellk24** [comment]
Keyboard now comes up from the bottom

**Comment by asm09fsu** [comment]
Perfect, looks good.
